Added italian translation
denysdovhan/wtfjs pull request #168
Opened 2020-11-11 10:00 UTC by ricsirigu

2020-11-12 11:30 UTC, denysdovhan requested changes
First of all, thank you for contributing ❤️

Please, find someone who speaks Italian to review and check the correctness of your translation.

2020-11-14 14:10 UTC, fmaule requested changes
Italian native speaker here.

Added a few suggestions and corrections - otherwise LGTM, and great job with the translation! It's always quite hard to decide where to translate a technical term in a different language. Often it's better to leave it in english because the translated version sounds absolutely awkward.

@denysdovhan thanks for maintaining this piece of art :)

2020-11-14 14:10 UTC, fmaule commented on README-it-it.md
> +Per farla breve, se `null` che è più piccolo di `0` è `false`, allora `null >= 0` è `true`. Leggi la spiegazione approfondita per questo [qui](https://blog.campvanilla.com/javascript-the-curious-case
più piccolo -> minore?

2020-11-14 14:10 UTC, fmaule commented on README-it-it.md
> +Invece, secondo una lettura attenta delle specifiche, la conversione a numero non avviente per l'operando che ha valore `null` o `undefined`. Quindi, se abbiamo `null` da un lato del simbolo uguale,
avviene*

2020-11-14 14:16 UTC, fmaule commented
Just noticed that I've added the review comments in Italian - thought it would be easier to understand. 
I can translate the suggestions as well, if needed.

2020-11-14 15:38 UTC, ricsirigu commented on README-it-it.md
> +Se non passiamo argomenti al costruttore di `Number`, otteniamo `0`. Il valore `undefined` viene assegnato ai parametri formale quando non viene passato alcun valore come parametro, quindi possiamo a
Cosa ne pensi di 

Il valore `undefined` viene assegnato come valore di default quando non viene passato alcun valore.

2020-11-14 15:42 UTC, ricsirigu commented on README-it-it.md
> +
Mi piace. 

Per la riga 530 cosa ne pensi di: 

"Altrimenti, `n` sarà il risultato di `ToNumber(value)`."

2020-11-14 15:53 UTC, ricsirigu commented
> Italian native speaker here.
> 
> Added a few suggestions and corrections - otherwise LGTM, and great job with the translation! It's always quite hard to decide where to translate a technical term in a different language. Often it's better to leave it in english because the translated version sounds absolutely awkward.
> 
> @denysdovhan thanks for maintaining this piece of art :)

Thanks for your effort @fmaule !

2020-11-16 13:49 UTC, fmaule commented on README-it-it.md
> +Se non passiamo argomenti al costruttore di `Number`, otteniamo `0`. Il valore `undefined` viene assegnato ai parametri formale quando non viene passato alcun valore come parametro, quindi possiamo a
Mi sembra perfetto - sorry mi era sfuggita la notifica 👍  potresti anche scrivere 
`Il valore undefined viene assegnato di default quando non viene passato alcun valore.` in quanto `il valore` è sottointeso

2020-11-19 14:18 UTC, denysdovhan approved these changes

2020-11-19 14:18 UTC, merged

2020-11-19 14:18 UTC, denysdovhan commented
Thanks for contributing!